# Build Settings
markdown: kramdown
theme: jekyll-theme-minimal
title: Bruce A. Lee
description: Data Analyst Portfolio 
logo: https://scontent.ftpa1-2.fna.fbcdn.net/v/t39.30808-6/272801652_10224169107589037_4412427858769561997_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=qKkkq-l7OLgAX9HwGav&tn=6JTXiNz933wdMRNh&_nc_ht=scontent.ftpa1-2.fna&oh=00_AfDsxFkdqA79-5KD0727tHEl9bYKJGOZvi1qW_BlOMgfDg&oe=63AFB026
show_downloads: false
